### ISSUE TITLE
Element request: CPTS

### ISSUE THREAD

**Issue by AtomicStarfish1** [JimmyHoke/The-Powder-Toy-Jimmy#2]
An element styled after the terraria biome, the corruption. It turns nearby pixels into the corrupted form of it, rather slowly (1 in 600 chance per frame for each pixel around it).

CPTS: The solid form of corruption (#410066 hex color). Turns solids into itself, liquids into CPTL, and gasses into CPTG.
CPTL: The liquid form of corruption (#4d2177 hex color). Turns liquids into itself, solids into CPTS, and gasses into CPTG.
CPTG: The gaseous form of corruption (#624872 hex color). Turns gasses into itself, solids into CPTS, and liquids into CPTL. 

Not really an issue, but an idea I had.

**Comment by JimmyHoke** [comment]
I've had this on the backburner for a while and finally did it.  Thanks for the idea.

**Comment by AtomicStarfish1** [comment]
Thanks so much! Gonna try it out right now!
